### PR TITLE
Fix age filter bug

### PR DESCRIPTION
**Pull request by em-cd**
This should fix an issue with the age filter where a user could filter by minimum age of 13, and see results for 2 to 4 year olds.

Also fixes a broken link in the README.

### CODE REVIEW

**Comment by dtt101** [comment]
Code looks solid - does it work in the UI?
I had got to a similar place in my thinking - I removed the comments from the PR - https://github.com/wearefuturegov/outpost-api-service/pull/10/commits/71bb9fa793bc5a29f6f1e6ec5394f0e87b0d9b9e

Only difference was I set min_age and max_age on every query regardless if they were provided or not, to make sure that things with null weren't returned

**Review by dtt101 — COMMENTED** [review]
Code looks solid - does it work in the UI?
I had got to a similar place in my thinking - I removed the comments from the PR - https://github.com/wearefuturegov/outpost-api-service/pull/10/commits/71bb9fa793bc5a29f6f1e6ec5394f0e87b0d9b9e

Only difference was I set min_age and max_age on every query regardless if they were provided or not, to make sure that things with null weren't returned

**Comment by em-cd** [comment]
I think it's fine to return things with null - those are shown as 'Suitable for all ages' in the UI. I never got around to implementing integration tests but I'm quite keen to get this in as it's been sitting around for ages! Smoke tests were all okay, are you happy for me to merge this @dtt101 ?

**Comment by dtt101** [comment]
@em-cd - let's merge!

**Pull request merged**
